### ISSUE TITLE
Cannot use proxies

### ISSUE THREAD

**Issue by BadSpider1** [crpmax/mc-bots#57]
Hello i use this command
`java -jar mc-bots-1.2.3.jar -s serverip -p BOT_ 5000 -c 400 -r -t SOCKS5 -l list.txt`
The error is
```
[16:43:58] INFO |  -> io.netty.handler.proxy.ProxyConnectException: socks5, none, /142.54.239.1:4145 => /89.187.158.222:45910, timeout
io.netty.handler.proxy.ProxyConnectException: socks5, none, /142.54.239.1:4145 => /89.187.158.222:45910, timeout
        at io.netty.handler.proxy.ProxyHandler$2.run(ProxyHandler.java:199)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:830)
```
This is my proxy list
```
1.117.117.154:2080
125.143.142.204:1080
142.54.239.1:4145
142.93.167.100:15307
143.198.136.154:55830
142.54.226.214:4145
143.198.212.163:55555
184.178.172.23:4145
182.43.41.33:9999
192.111.139.163:19404
212.152.35.114:1080
205.240.77.164:4145
43.154.24.245:8888
47.242.12.237:10088
72.206.181.105:64935
64.192.91.55:10000
68.1.210.163:4145
68.71.249.153:48606
72.210.221.197:4145
65.169.38.73:26592
109.206.182.50:1080
159.65.188.178:11196
188.165.206.113:13853
```
I use 
OpenJDK 13.07

**Comment by BadSpider1** [comment]
Now im having this issue
Exception in thread "main" java.lang.NullPointerException
        at me.creepermaxcz.mcbots.Main.main(Main.java:233)

**Comment by BadSpider1** [comment]
I am not trying to bot any such ip me.creepermaxcz
